name: Python autotests in zip

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: choose tests set
        required: true
        type: choice
        default: smoke
        options:
          - smoke
          - regression
          - extended
          - extended_failed
          - all

#permissions: 
  #contents: read
  #pages: write
  #id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    name: Run autotests
    steps:
      - name: Checkout autotests
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies.
        run: pip install -r requirements.txt
      - name: run all tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest --alluredir=allure-results
        continue-on-error: true
      - name: run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: pytest test_tests_allure.py::test_post_greate_mat --alluredir=allure-results
        continue-on-error: true
      - name: run regression tests
        if: "github.event.inputs.deployment_target == 'regression'"
        run: pytest -m regression --alluredir=allure-results
        continue-on-error: true
      - name: run extended tests
        if: "github.event.inputs.deployment_target == 'extended'"
        run: pytest -m extended --alluredir=allure-results
        continue-on-error: true
      - name: run extended_failed tests
        if: "github.event.inputs.deployment_target == 'extended_failed'"
        run: pytest -m extended_failed --alluredir=allure-results
        continue-on-error: true
        
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Install Allure
        run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.tgz && sudo tar -zxvf allure-2.24.1.tgz -C /opt/ && sudo ln -s /opt/allure-2.24.1/bin/allure /usr/bin/allure
      - name: Generate report
        #run: allure generate -c allure-results -o _site
        run: allure generate -c allure-results -o allure-report
      - name: Save allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          #name: _site
          #path: _site
          retention-days: 7
  
 # publish-report:
    #runs-on: ubuntu-22.04
    #needs: run-tests
    #steps:
      #- name: Download artifacts
       # uses: actions/download-artifact@v3
      #- name: Upload Pages artifact
      #  uses: actions/upload-pages-artifact@v2
      #- name: Deploy to GitHub Pages
      #  id: deployment
      # 3 uses: actions/deploy-pages@v1.2.9
